config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resource :qr_code, only: %i[new create]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root to: 'qr_codes#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/qr_codes_controller.rb
# frozen_string_literal: true

class QrCodesController < ApplicationController
  def new; end

  def create
    qrcode = RQRCode::QRCode.new(link)

    @name = name

    png = qrcode.as_png(
      bit_depth:         1,
      border_modules:    4,
      color_mode:        ChunkyPNG::COLOR_GRAYSCALE,
      color:             'black',
      file:              "app/assets/images/qr_codes/#{name}.png",
      fill:              'white',
      module_px_size:    6,
      resize_exactly_to: false,
      resize_gte_to:     false,
      size:              240
    )
    File.binwrite("app/assets/images/qr_codes/#{name}.png", png.to_s)
    send_pdf
  end

  private

  def send_pdf
    file = File.read("app/assets/images/qr_codes/#{@name}.png")

    send_data file, filename: "#{@name}.png"
  end

  def name
    params[:qr_code][:name]
  end

  def link
    params[:qr_code][:link]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Qr</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/qr_codes/new.html.slim
.colored
  h2 Введите ссылку
  = form_for :qr_code, url: qr_code_path do |f|
    .field
      = f.label :link, 'Ссылка'
      = f.text_field :link, required: true
    .field
      = f.label :name, 'Название'
      = f.text_field :name
    .submit = f.submit 'Сгенерировать QR Code', class: 'button expanded', required: true